######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 18 23:20:56 2012
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/Mail.hpp src/SMTPClient.hpp
SOURCES += src/Mail.cpp src/main.cpp src/SMTPClient.cpp
